version: '3.7'
services:
  db:
    container_name: vnoj_mysql
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./database/:/var/lib/mysql/
    env_file: [environment/mysql.env, environment/mysql-admin.env]
    networks: [db]
    #ports:
    #  - 3306:3306
  redis:
    container_name: vnoj_redis
    image: redis:alpine
    restart: unless-stopped
    networks: [site]
    #ports:
    #  - 6379:6379
  texoid:
    build:
      context: .
      dockerfile: ./texoid/Dockerfile
    image: hieplpvip/vnoj-texoid
    restart: unless-stopped
    networks: [site]
  mathoid:
    build:
      context: .
      dockerfile: ./mathoid/Dockerfile
    image: hieplpvip/vnoj-mathoid
    restart: unless-stopped
    volumes:
      - ./mathoid/config.yaml:/node_modules/mathoid/config.yaml
    networks: [site]
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: hieplpvip/vnoj-base
    network_mode: none
  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    image: hieplpvip/vnoj-site
    restart: unless-stopped
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./logs/:/logs/
      - ./media/:/media/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    depends_on: [base]
  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: hieplpvip/vnoj-celery
    restart: unless-stopped
    volumes:
      - datacache:/datacache/
      - ./logs/:/logs/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db]
    depends_on: [base]
  bridged:
    build:
      context: .
      dockerfile: ./bridged/Dockerfile
    image: hieplpvip/vnoj-bridged
    restart: unless-stopped
    volumes:
      - ./logs/:/logs/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    ports:
      - 9998:9998
      - 9999:9999
    depends_on: [base, db, redis]
  wsevent:
    build:
      context: .
      dockerfile: ./wsevent/Dockerfile
    image: hieplpvip/vnoj-wsevent
    restart: unless-stopped
    volumes:
      - ./repo/:/app/site/
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]
    #ports:
    #  - 15100:15100
    #  - 15101:15101
    #  - 15102:15102
  nginx:
    container_name: vnoj_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./logs/:/logs/
      - ./media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site, wsevent]
networks:
  site:
  db:
  nginx:
volumes:
  assets:
  pdfcache:
  datacache:
  cache:
